force-app/main/default/objects/Athlete__c/Athlete__c.object-meta.xml
<CustomObject>
    <label>Athlete</label>
    <nameField>
        <label>Athlete Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Athletes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Athlete__c/fields/All_Ride_Count__c.field-meta.xml
<CustomField>
    <fullName>All_Ride_Count__c</fullName>
    <label>All Ride Count</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/All_Ride_Distance__c.field-meta.xml
<CustomField>
    <fullName>All_Ride_Distance__c</fullName>
    <label>All Ride Distance</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/All_Ride_Elapsed_Time__c.field-meta.xml
<CustomField>
    <fullName>All_Ride_Elapsed_Time__c</fullName>
    <label>All Ride Elapsed Time</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/All_Ride_Elevation_Gain__c.field-meta.xml
<CustomField>
    <fullName>All_Ride_Elevation_Gain__c</fullName>
    <label>All Ride Elevation Gain</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/All_Ride_Moving_Time__c.field-meta.xml
<CustomField>
    <fullName>All_Ride_Moving_Time__c</fullName>
    <label>All Ride Moving Time</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Biggest_Climb_Elevation_Gain__c.field-meta.xml
<CustomField>
    <fullName>Biggest_Climb_Elevation_Gain__c</fullName>
    <label>Biggest Climb Elevation Gain</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Biggest_Ride_Distance__c.field-meta.xml
<CustomField>
    <fullName>Biggest_Ride_Distance__c</fullName>
    <label>Biggest Ride Distance</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Ride_Achievement_Count__c.field-meta.xml
<CustomField>
    <fullName>Recent_Ride_Achievement_Count__c</fullName>
    <label>Recent Ride Achievement Count</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Ride_Count__c.field-meta.xml
<CustomField>
    <fullName>Recent_Ride_Count__c</fullName>
    <label>Recent Ride Count</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Ride_Distance__c.field-meta.xml
<CustomField>
    <fullName>Recent_Ride_Distance__c</fullName>
    <label>Recent_Ride_Distance</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Ride_Elapsed_Time__c.field-meta.xml
<CustomField>
    <fullName>Recent_Ride_Elapsed_Time__c</fullName>
    <label>Recent Ride Elapsed Time</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Ride_Elevation_Gain__c.field-meta.xml
<CustomField>
    <fullName>Recent_Ride_Elevation_Gain__c</fullName>
    <label>Recent Ride Elevation Gain</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Ride_Moving_Time__c.field-meta.xml
<CustomField>
    <fullName>Recent_Ride_Moving_Time__c</fullName>
    <label>Recent Ride Moving Time</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Run_Count__c.field-meta.xml
<CustomField>
    <fullName>Recent_Run_Count__c</fullName>
    <label>Recent Run Count</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Run_Distance__c.field-meta.xml
<CustomField>
    <fullName>Recent_Run_Distance__c</fullName>
    <label>Recent Run Distance</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Run_Elapsed_Time__c.field-meta.xml
<CustomField>
    <fullName>Recent_Run_Elapsed_Time__c</fullName>
    <label>Recent Run Elapsed Time</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Run_Elevation_Gain__c.field-meta.xml
<CustomField>
    <fullName>Recent_Run_Elevation_Gain__c</fullName>
    <label>Recent Run Elevation Gain</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Athlete__c/fields/Recent_Run_Moving_Time__c.field-meta.xml
<CustomField>
    <fullName>Recent_Run_Moving_Time__c</fullName>
    <label>Recent Run Moving Time</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AthleteController.cls
public with sharing class AthleteController {
    @AuraEnabled(cacheable=true)
    public static Athlete__c getAthleteData(String athleteId) {
        // Query the athlete data
        return [SELECT Id, Recent_Ride_Count__c, Recent_Ride_Distance__c, Recent_Ride_Moving_Time__c, Recent_Ride_Elapsed_Time__c, Recent_Ride_Elevation_Gain__c, Recent_Ride_Achievement_Count__c, All_Ride_Count__c, All_Ride_Distance__c, All_Ride_Moving_Time__c, All_Ride_Elapsed_Time__c, All_Ride_Elevation_Gain__c, Biggest_Ride_Distance__c, Biggest_Climb_Elevation_Gain__c, City__c, Country__c, First_Name__c, Last_Name__c, Profile_Picture_Formula__c, Profile_Picture__c, Recent_Run_Count__c, Recent_Run_Distance__c, Recent_Run_Elapsed_Time__c, Recent_Run_Elevation_Gain__c, Recent_Run_Moving_Time__c FROM Athlete__c WHERE Id = :athleteId LIMIT 1];
    }
}